name: Generate Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Pac-Man Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: MatheusMartinsN1
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: Generate contribution graph
          add: ./output
          push: true
          github_token: ${{ secrets.GH_TOKEN }}

